name: Sponsors Updater

on:
  workflow_dispatch:
  schedule:
    - cron: "5 0 * * *"

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sponsors
    steps:
      - uses: actions/checkout@v2

      - name: Set node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npx pnpm i

      - name: Update sponsors
        run: npm run build
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          SPONSORKIT_GITHUB_LOGIN: kashalls

      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          message: "chore: update sponsors.svg"
          add: "./sponsors/sponsors.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}