name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  
jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "FALSE"
          SHOW_LINES_OF_CODE: "FALSE"
          SHOW_PROFILE_VIEWS: "FALSE" # I dont care about how many views i get
          SHOW_EDITORS: "FALSE" # VS CODE
          SHOW_OS: "FALSE" # I only use Windows and Arch
          SHOW_LOC_CHART: "FALSE"
